version: '3.8'

services:
  # Development Service
  client:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - ENV=local
    volumes:
      - .:/app
      - /app/node_modules

