version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: levelsliving
      POSTGRES_PASSWORD: password
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  server:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/levelsliving
      SECRET_KEY: ${SECRET_KEY}
      # --- ADD OR UPDATE THESE LINES ---
      GOOGLE_GENAI_PROJECT_ID: "levelslivingai"
      GOOGLE_GENAI_USE_VERTEXAI: "False" # Make sure this is False
      GOOGLE_GENAI_LOCATION: "global"

      # Add your new API Key here
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    restart: always
    volumes:
      - .:/app

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  pgadmin_data:
