name: Build and Test Server

on:
  push:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Set up Docker
        run: |
          sudo service docker start
          docker info

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt

      - name: Run pytest
        env:
          DOCKER_HOST: unix:///var/run/docker.sock  # Ensure Docker is accessible
        run: |
          pytest server/tests